name: Release

on:
  pull_request:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # push git tags 
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4            
    
      - name: simulate merging pull request 
        id: simulate_merge
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/simulate_merge

      - name: Semantic Release
        uses: ./
        id: semantic
        with:
          simulate_push_branch: ${{ steps.simulate_merge.outputs.branch_name }}
          dry_run: ${{ github.event_name == 'pull_request' }}
          branches: |
            [
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/github
            semantic-release-recovery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  major-version-bump: # update major version tags (ex: v1, v2, v3, etc.)
    runs-on: ubuntu-latest
    needs: release
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.GENERATE_TOKEN_APP_ID }}
          private_key: ${{ secrets.GENERATE_TOKEN_PRIVATE_KEY_B64 }}

      - uses: levibostian/action-bump-major-tag@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}